# Generated by Django 2.1.7 on 2019-03-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=30)),
                ('price', models.PositiveSmallIntegerField()),
                ('available', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returndate', models.DateField()),
                ('issuedate', models.DateField()),
                ('duedate', models.DateField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('clid', models.IntegerField(primary_key=True, serialize=False)),
                ('roomno', models.PositiveSmallIntegerField()),
                ('block', models.CharField(max_length=20)),
                ('startime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('credit', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dnum', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
                ('dnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Department')),
            ],
        ),
        migrations.CreateModel(
            name='FeesInf',
            fields=[
                ('feid', models.IntegerField(primary_key=True, serialize=False)),
                ('fename', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.IntegerField()),
                ('block', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('memid', models.IntegerField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course')),
                ('dnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out', models.DateTimeField()),
                ('ent', models.DateTimeField()),
                ('reason', models.TextField()),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preid', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('roomno', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
                ('nbeaded', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StdentMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='male', max_length=10)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('father', models.CharField(default='non', max_length=30)),
                ('fathers_occupation', models.CharField(default='non', max_length=50)),
                ('mother', models.CharField(default='non', max_length=30)),
                ('mothers_occupation', models.CharField(default='non', max_length=50)),
                ('house_no', models.SmallIntegerField(default=123)),
                ('locality', models.CharField(default='non', max_length=200)),
                ('city', models.CharField(default='non', max_length=50)),
                ('state', models.CharField(default='non', max_length=100)),
                ('pin', models.IntegerField(default=123456)),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendence', models.IntegerField()),
                ('clid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('regno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vit.Student')),
                ('tution', models.IntegerField()),
                ('hostel', models.IntegerField()),
                ('mess', models.IntegerField()),
                ('hdues', models.SmallIntegerField()),
                ('ldues', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='take',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='vit.Department'),
        ),
        migrations.AddField(
            model_name='stdentmob',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Student'),
        ),
        migrations.AddField(
            model_name='outing',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Student'),
        ),
        migrations.AddField(
            model_name='login',
            name='regno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vit.Student'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='roommo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.RoomDetails'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='memid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Library'),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('fid', 'cid')},
        ),
        migrations.AlterUniqueTogether(
            name='take',
            unique_together={('clid', 'regno')},
        ),
        migrations.AlterUniqueTogether(
            name='stdentmob',
            unique_together={('mobile', 'regno')},
        ),
        migrations.AlterUniqueTogether(
            name='offers',
            unique_together={('dnum', 'cid')},
        ),
        migrations.AlterUniqueTogether(
            name='enrolled',
            unique_together={('cid', 'regno')},
        ),
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together={('memid', 'bookid')},
        ),
    ]
