# Generated by Django 2.1.7 on 2019-03-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='regno',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
