# Generated by Django 2.1.7 on 2019-03-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0004_auto_20190321_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='grade',
        ),
    ]
