# Generated by Django 2.1.7 on 2019-03-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0006_enrolled_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='library',
            name='memid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
