# Generated by Django 2.1.7 on 2019-03-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0007_auto_20190323_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returndate',
            field=models.DateField(null=True),
        ),
    ]
