# Generated by Django 2.1.7 on 2019-03-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0008_auto_20190323_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='hid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vit.Hostel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returndate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
