# Generated by Django 2.1.7 on 2019-03-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0010_auto_20190323_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hid',
        ),
    ]
