# Generated by Django 2.1.7 on 2019-03-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0011_remove_student_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vit.Hostel'),
        ),
    ]
