# Generated by Django 2.1.7 on 2019-03-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0012_student_hid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='block',
        ),
    ]
