# Generated by Django 2.1.7 on 2019-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0013_remove_class_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='attendence',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=6),
        ),
    ]
