# Generated by Django 2.1.7 on 2019-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0014_auto_20190323_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hdues',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='hostel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ldues',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mess',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='take',
            name='attendence',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=9),
        ),
    ]
