# Generated by Django 2.1.7 on 2019-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0015_auto_20190323_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hostel',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mess',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='tution',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
