# Generated by Django 2.1.7 on 2019-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0016_auto_20190323_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='address',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
