# Generated by Django 2.1.7 on 2019-03-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0017_auto_20190323_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mat', models.FileField(upload_to='')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vit.Course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default="{%static 'vit\\images\\pw.jpg'%}", upload_to=''),
        ),
    ]
