# Generated by Django 2.1.7 on 2019-03-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vit', '0018_auto_20190323_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vit.Faculty'),
        ),
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='mat',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('fid', 'cid')},
        ),
    ]
